FROM python:3.13-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.9.15 /uv /uvx /bin/

# OCI formatted labels
LABEL \
    org.opencontainers.image.title="IMGNAMEPLACEHOLDER" \
    org.opencontainers.image.authors="<mfoster11@mgh.harvard.edu>" \
    org.opencontainers.image.url="https://github.com/mjfos2r/containers/IMGNAMEPLACEHOLDER" \
    org.opencontainers.image.description="UV managed python container for IMGNAMEPLACEHOLDER" \
    org.opencontainers.image.version="0.0.1"

# installed tools are available immediately
ENV UV_TOOL_BIN_DIR=/usr/local/bin
# enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Install deps
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    ca-certificates \
    # add more deps here
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# install tools from pip
RUN uv tool install NEWTOOL

####################################################
##### if this container is for a python project ####
## Install the project's dependencies using the lockfile and settings
#RUN --mount=type=cache,target=/root/.cache/uv \
#    --mount=type=bind,source=uv.lock,target=uv.lock \
#    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
#    uv sync --locked --no-install-project --no-dev
#
## add the rest of the project
#ADD . /app
#WORKDIR /app
#RUN uv sync --locked
## and add the newly installed executables onto our path.
#ENV PATH="/app/.venv/bin:$PATH"
####################################################


# Verify installation
RUN for cmd in tool1 tool2 tool3; do \
    command -v cmd &>/dev/null || exit 1; \
    done

# Set entrypoint
ENTRYPOINT [ "/bin/bash" ]
