FROM debian:bookworm-slim

# OCI formatted labels
LABEL \
    org.opencontainers.image.title="IMGNAMEPLACEHOLDER" \
    org.opencontainers.image.authors="<mfoster11@mgh.harvard.edu>" \
    org.opencontainers.image.url="https://github.com/mjfos2r/containers/IMGNAMEPLACEHOLDER" \
    org.opencontainers.image.description="Debian bookworm-slim container for IMGNAMEPLACEHOLDER" \
    org.opencontainers.image.version="0.0.1"

# Install deps
RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    curl \
    make \
    # Add additional dependencies here
    && apt-get clean \
    && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

# Setup directories
RUN mkdir -p /data /output /opt/tool

# Download and install tool
RUN curl -LsSf https://URLTODOWNLOAD.com/whatever/this/link/is.tar.gz \
    | tar xzv -C /tmp/tool --strip-components=1 --no-same-owner \
    ... stuff for installation \
    && cd /tmp/tool \
    && ./configure --your-configure-options \
    && make \
    && make install

# Verify installation
RUN for cmd in tool1 tool2 tool3; do \
    command -v cmd &>/dev/null || exit 1; \
done

# Set working directory
WORKDIR /opt

COPY [ "entrypoint.sh", "script.sh", "/opt/" ]

# Make scripts executable
RUN chmod +x /opt/entrypoint.sh /opt/script.sh

# Set entrypoint
ENTRYPOINT [ "/bin/bash", "entrypoint.sh" ]